### ISSUE TITLE
Optimise webpack build file

### ISSUE THREAD

**Issue by mbad0la** [o-d-i-n/HelloWorld#15]
@ayushgarg1804 can you put up some stats regarding this?

**Comment by ayushgarg1804** [comment]
@mbad0la [Google Speed analysis](https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fnsitod.in%2F&tab=desktop) for just **minifying** js says  

> Minifying https://nsitod.in/static/js/bundle.js could save 444.7KiB (44% reduction).

**Comment by prabhakar267** [comment]
I don't think it would be a good idea to manually minify CSS and JS files!
@mbad0la maybe we can look for some external app to do this for us automatically?

**Comment by mbad0la** [comment]
@prabhakar267 we don't have to do it manually. It can part of the build process itself.

**Comment by manrajgrover** [comment]
@mbad0la I would suggest gzipping your resources. This saves a lot of network bandwidth. How to do it? You need to change your server configuration.

**Comment by mbad0la** [comment]
@ManrajGrover we are using Django for backend. Does it have some in-built methods for gzipping resources?
**Notify** :  @prabhakar267

**Comment by manrajgrover** [comment]
@mbad0la Quick search gave me this: https://docs.djangoproject.com/en/1.10/ref/middleware/#module-django.middleware.gzip

You can look into it.

**Comment by ab-decoded** [comment]
We can use grunt/gulp for minification.Each time a change occurs in js/css occurs, it will minify it auromatically.

**Comment by manrajgrover** [comment]
@ab-decoded Yeps, you can. Since the issue mentions Webpack, I guess it is already being used. Haven't checked though. If yes, Webpack too provides ways to minify code. If not, gulp/grunt can serve well for this.

**Comment by mbad0la** [comment]
@o-d-i-n/helloworld have a look at this interesting [article](https://blog.engineyard.com/2016/tree-shaking) 

We should implement tree shaking to further optimize our build file.

**Comment by ayushgarg1804** [comment]
@mbad0la ek baar minify wala confirm kardo I'll add gzip compression :P first because I guess gzip se zyada kam hogi file than tree shaking.

**Comment by mbad0la** [comment]
Closing this for now.
