### ISSUE TITLE
Create CONTRIBUTORS.md

### ISSUE THREAD

**Issue by prabhakar267** [o-d-i-n/HelloWorld#16]
Instead of mentioning the contributors list in [README.md](https://github.com/o-d-i-n/HelloWorld/blob/master/README.md), create a new file CONTRIBUTORS.md and mention it there!

**Comment by Pranav-Rastogi** [comment]
Dear sir, 
I would like to make this contribution so if someone else is not working on this kindly allow me to.

**Comment by mbad0la** [comment]
Hey @Pranav-Rastogi !

Please follow [all-contributors specs](https://github.com/kentcdodds/all-contributors) while creating the `CONTRIBUTORS.md`

Also remove any irrelevant contributor information from `README.md` and instead add a small footer to redirect to `CONTRIBUTORS.md` on the README

**Comment by Pranav-Rastogi** [comment]
Dear Sir,
I have initiated a PR for this issue. I have added a `contributors.md` file and have also put a link to it in the `Readme.md` file. I have further added a contributors.py to the PR that can be used in future to make a contributors.md automatically. This contributor.md was also created using that file.

**Comment by mbad0la** [comment]
Closing this up. Thanks @Pranav-Rastogi!
