### ISSUE TITLE
Handle serving gzipped resources

### ISSUE THREAD

**Issue by mbad0la** [o-d-i-n/HelloWorld#19]
Courtesy #18 , we will have a gzipped bundle which won't get resolved on the client side. Make appropriate response header changes to accommodate this functionality. 

Feedback would be wonderful if you think things are working fine already.

**Comment by mbad0la** [comment]
Did we resolve this @ayushgarg1804 ?

**Comment by ayushgarg1804** [comment]
Not yet, will do it soon

**Comment by mbad0la** [comment]
@ayushgarg1804 , @mananpal1997 will be working on repro of this issue and come up with a strategy on how to proceed

**Comment by mbad0la** [comment]
@ayushgarg1804 , @mananpal1997 it seems the browser is smart enough to resolve compressed bundle :tada: 
Closing the issue.

**Comment by ayushgarg1804** [comment]
Haha, I told you before just wasn't sure about it.

**Comment by mananpal1997** [comment]
@mbad0la I was trying to tell same thing the other day, couldn't figure out properly though. 😄
