### ISSUE TITLE
Error while executing sudo pip install -r requirements.txt

### ISSUE THREAD

**Issue by manan904** [o-d-i-n/HelloWorld#27]
Received the following error:
```
EnvironmentError: mysql_config not found
Command "python setup.py egg_info" failed with error code 1 in /private/tmp/pip-build-RIBICf/MySQL-python/
```

Also getting an issue while executing "python manage.py migrate" 
```
from config import MYSQL_USERNAME, MYSQL_PASSWORD, MYSQL_HOSTNAME, MYSQL_DATABASE
ImportError: No module named config
```

**Comment by mbad0la** [comment]
Hey @manan904 
Make sure you have :
* mysql installed
* and setup `config.py` file with mysql credentials. A sample config is located [here](https://github.com/o-d-i-n/HelloWorld/blob/4d23f894a223347a62e3b8e68ad24cca738e091a/helloWorld/config.py.sample)

**Comment by gabru-md** [comment]
config.py file is named as config.py.sample.
This causes the import error.
And enter the credentials. That will certainly do.

**Comment by manan904** [comment]
Downloaded mysql.
No errors. 
Thanks!
