### ISSUE TITLE
favicon is missing

### ISSUE THREAD

**Issue by gabru-md** [o-d-i-n/HelloWorld#28]
favicon is missing from the webpage.
may I add it ?

**Comment by mbad0la** [comment]
What do you propose as our favicon?

**Comment by gabru-md** [comment]
i guess that the ODIN-Logo will do.
![](https://avatars2.githubusercontent.com/u/17124736?v=4&s=200)

#Edit: I meant to say that the statement
```
<link rel="icon" type="image/x-icon" href="path/to/favicon.ico">
```
is missing from index.html and must be added. :D

**Comment by mbad0la** [comment]
Sure, go ahead. Don't forget to add relevant screenshot!

**Comment by mananpal1997** [comment]
@mbad0la close it and merge the pr?

**Comment by mbad0la** [comment]
Yeah.
