### ISSUE TITLE
Dev setup needs to be documented in README.md

### ISSUE THREAD

**Issue by mbad0la** [o-d-i-n/HelloWorld#30]
The documentation for locally setting up the project is incomplete

**Comment by pratyush1687** [comment]
is this issue closed?

**Comment by mbad0la** [comment]
@rrsk  can you confirm this?

**Comment by rrsk** [comment]
Yeah I believe it is.

**Comment by mbad0la** [comment]
Closing this issue. Thanks @pratyush1687 @rrsk for helping us clear up this issue.
